# Generated by Django 4.2.4 on 2023-09-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_do_carro', models.IntegerField(default=0)),
                ('marca_do_carro', models.CharField(max_length=20)),
                ('modelo_do_carro', models.CharField(max_length=20)),
                ('ano_do_carro', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_da_moto', models.IntegerField(default=0)),
                ('marca_da_moto', models.CharField(max_length=20)),
                ('modelo_da_moto', models.CharField(max_length=20)),
                ('ano_da_moto', models.CharField(max_length=4)),
                ('cilindrada_da_moto', models.CharField(max_length=5)),
            ],
        ),
    ]
