# Generated by Django 4.2.4 on 2023-09-02 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carro',
            name='id_do_carro',
        ),
        migrations.RemoveField(
            model_name='moto',
            name='id_da_moto',
        ),
    ]
